# Generated by Django 3.1.6 on 2021-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastValue',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start', models.FloatField(max_length=100)),
                ('high', models.FloatField(max_length=100)),
                ('low', models.FloatField(max_length=100)),
                ('end', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.IntegerField(default=5, max_length=100)),
                ('long', models.IntegerField(default=14, max_length=100)),
                ('val', models.IntegerField(default=30, max_length=100)),
                ('sjpy', models.IntegerField(default=100, max_length=100)),
            ],
        ),
    ]
