# Generated by Django 3.1.6 on 2021-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveline', models.IntegerField(default=20, verbose_name='移動平均線（日）')),
                ('val', models.IntegerField(default=30, verbose_name='取引量（％）')),
                ('sjpy', models.IntegerField(default=100000, verbose_name='初期投資額（円）')),
            ],
        ),
        migrations.CreateModel(
            name='PastValue',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('start', models.FloatField(max_length=100)),
                ('high', models.FloatField(max_length=100)),
                ('low', models.FloatField(max_length=100)),
                ('end', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.IntegerField(default=5, verbose_name='短い移動平均線')),
                ('long', models.IntegerField(default=14, verbose_name='長い移動平均線')),
                ('val', models.IntegerField(default=30, verbose_name='取引量（％）')),
                ('sjpy', models.IntegerField(default=100, verbose_name='初期投資額（JPY）')),
            ],
        ),
    ]
