# Generated by Django 3.1.6 on 2021-11-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ju', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sma',
            name='long',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='sma',
            name='short',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sma',
            name='sjpy',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='sma',
            name='val',
            field=models.IntegerField(default=30),
        ),
    ]
