# Generated by Django 3.1.6 on 2021-11-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ju', '0002_auto_20211117_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveline', models.IntegerField(default=20, verbose_name='移動平均線（日）')),
                ('val', models.IntegerField(default=30, verbose_name='取引量（％）')),
                ('sjpy', models.IntegerField(default=100000, verbose_name='初期投資額（円）')),
            ],
        ),
        migrations.AlterField(
            model_name='pastvalue',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sma',
            name='long',
            field=models.IntegerField(default=14, verbose_name='長い移動平均線'),
        ),
        migrations.AlterField(
            model_name='sma',
            name='short',
            field=models.IntegerField(default=5, verbose_name='短い移動平均線'),
        ),
        migrations.AlterField(
            model_name='sma',
            name='sjpy',
            field=models.IntegerField(default=100, verbose_name='初期投資額（JPY）'),
        ),
        migrations.AlterField(
            model_name='sma',
            name='val',
            field=models.IntegerField(default=30, verbose_name='取引量（％）'),
        ),
    ]
